language: ruby
rvm:
  - 2.2.1
  
script:
  - cd spec/dummy
  - rake db:create
  - rake db:migrate
  - cd ../..
  - rake

addons:
  code_climate:
    repo_token: 2b435d14ec6573f6a3bdd7e858a5da4665d7e6968e5309c691cc80f1dcc14d40
